name: hackpl.us
favicon: null
layout_spectrum: 0.7358077559620142
typography_spectrum: 0.2944050352089107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8325784567277879
  lightness: 0.547954446868971
  saturation: 0.7966884574852884
  rhythmicContrast: 0.8249380895867944
purpose: []
